### ISSUE TITLE
关于HtFE3模型下的Cifar100实验的参数配置

### ISSUE THREAD

**Issue by maxwellgodv** [TsingZ0/FedTGP#2]
你好，我想复现HtFE3模型配置下的Cifar100实验。我根据论文中提到的参数进行实验，但离论文中的准确率有较大的差距。`nohup python -u main.py -t 3 -ab 1 -lr 0.01 -jr 1 -lbs 10 -ls 1 -nc 20 -nb 100 -data Cifar100_20client_dir -m HtFE3 -fd 512 -did 0 -algo FedTGP -lam 10 -se 100 -mart 100  > Cifar100-HtFE3-fd=512-FedTGP.out 2>&1 &`这是我的运行代码，请问是我哪个参数设置错了吗？Cifar100数据是practical setting的，20个客户端，由[PFLlib](https://github.com/TsingZ0/PFLlib/blob/master/dataset/generate_Cifar100.py)生成的。下面是数据的config.json `{"num_clients":20,"num_classes":100,"non_iid":true,"balance":false,"partition":"dir","alpha":0.1,"batch_size":10}`

**Comment by TsingZ0** [comment]
FedTGP中Server上的训练比较困难，尤其是任务的类别个数比较多的时候，设置较大的`top_cnt`比较合适，最好运行1000轮以上，且从头开始运行多次后取平均结果。其中一个判断FedTGP是否成功训练的方法是：观察`Server loss`的大小。根据训练时的经验，对于Cifar100这个100分类问题来说，如果`Server loss`降低到0.001以下（最好是0.00001以下），TGP基本上算是训练成功了，这时候acc会有个较大的跃升。在我们的实验中可以看到`Server loss=0.0`的时候FedTGP取得最佳acc。

**Comment by maxwellgodv** [comment]
非常感谢您的回复。我还有个问题，就是论文中的其他方法的实验是用[HtFLlib](https://github.com/TsingZ0/HtFLlib/tree/main)实现的吗？我使用HtFE3模型，在dir设置的Cifar100上进行实验LG-FedAvg和FedGH，但是达不到论文中的准确率，请问是一些参数没配置对吗？下面是我的运行代码。
`nohup python -u main.py  -t 1 -ab 1 -lr 0.01 -jr 1 -lbs 10 -ls 1 -nc 20 -nb 100 -data Cifar100_20client_dir -m HtFE3 -did 0 -algo FedGH -slr 0.01`
`nohup python -u main.py -t 1 -ab 1 -lr 0.01 -jr 1 -lbs 10 -ls 1 -nc 20 -nb 100 -data Cifar100_20client_dir -m HtFE3 -did 0 -algo LG-FedAvg `

**Comment by TsingZ0** [comment]
FedGH需设置`-se 1`。准确率相差多少呢？可能是[PFLlib](https://github.com/TsingZ0/PFLlib)中的数据集生成代码经过版本更新后，导致生成的数据有些许差距吧，如果准确率相差不大还是可以接受的

**Comment by maxwellgodv** [comment]
感谢您的回复，我在我的机器上跑，FedGH差了2%左右，LG-FedAvg差了1%左右。按照[FedKTL](https://github.com/TsingZ0/FedKTL)中的结果，FedGH应该和LG-FedAvg的准确率是差不多的。我在pat设置的cifar100上进行实验，FedGH和LG-FedAvg显示的结果是差不多的。但在dir设置的cifar100上，FedGH和LG-FedAvg结果差距有点大，差距超过了1%。

**Comment by TsingZ0** [comment]
dir的数据集生成方式最近按照大家的要求进行了多次更新，pat基本上没有改动。考虑到还有机器型号不同等问题，这个acc差距也在合理范围内，一般看横向对比的相对数值比较合理
