### ISSUE TITLE
关于论文中超参数lamda的选择

### ISSUE THREAD

**Issue by wisheverybodyhapi** [TsingZ0/FedTGP#3]
作者你好，我在阅读您的FedTGP论文时，发现实验部分写的是lamda设置为了0.1。我相信论文中给出的应该是性能最好的参数。
We set λ = 0.1 (the same as FedProto), τ = 100, and S = 100 (the number of server training epochs) for our FedTGP on all tasks.

但是您的shell脚本中，lamda参数设置为了10
nohup python -u main.py -t 3 -ab 1 -lr 0.01 -jr 1 -lbs 10 -ls 1 -nc 20 -nb 10 -data Cifar10 -m HtFE8 -fd 512 -did 3 -algo FedTGP -lam 10 -se 100 -mart 100 > total-Cifar10-HtFE8-fd=512-FedTGP.out 2>&1 &

请问我该以哪个为标准？

**Comment by TsingZ0** [comment]
These two lambda are different. Please differentiate the Euclidean distance with MSE. We also set lambda to 10 for FedProto
