### ISSUE TITLE
关于batch_size的选择

### ISSUE THREAD

**Issue by CharlesLayn** [TsingZ0/FedTGP#4]
作者你好！想请问一下有可能在更大的batch_size的设置下实现论文里的结果吗？ 因为batch_size为10训练时间会长非常多，想请问一下作者是怎么解决这个问题的？谢谢~

**Comment by TsingZ0** [comment]
目前没有，我们follow之前的工作，设置固定的batch size为10。主要是因为考虑到client上的训练资源有限，所以不能使用较大的batch size
